import os
import sqlite3
from pathlib import Path
from urllib.parse import urlparse


SQLITE_SCHEMA = """
create table if not exists source_files (
  id integer primary key,
  path text not null unique,
  name text not null,
  sha256 text not null,
  mtime real not null,
  imported_at text not null
);

create table if not exists trend_queries (
  id integer primary key,
  source_file_id integer not null references source_files(id) on delete cascade,
  source_row integer not null,
  geo text not null,
  category text not null,
  date_range text not null,
  query text not null,
  translation_original text not null default '',
  translation_ai text not null default '',
  change_label text not null default '',
  change_value integer,
  change_is_breakout integer not null default 0,
  imported_at text not null,
  unique(source_file_id, source_row)
);

create table if not exists translation_cache (
  query text primary key,
  translation_ai text not null,
  model text not null,
  updated_at text not null
);

create index if not exists idx_trend_geo on trend_queries(geo);
create index if not exists idx_trend_category on trend_queries(category);
create index if not exists idx_trend_change_value on trend_queries(change_value);
create index if not exists idx_trend_query on trend_queries(query);
"""


POSTGRES_SCHEMA = """
create table if not exists source_files (
  id integer generated by default as identity primary key,
  path text not null unique,
  name text not null,
  sha256 text not null,
  mtime double precision not null,
  imported_at text not null
);

create table if not exists trend_queries (
  id integer generated by default as identity primary key,
  source_file_id integer not null references source_files(id) on delete cascade,
  source_row integer not null,
  geo text not null,
  category text not null,
  date_range text not null,
  query text not null,
  translation_original text not null default '',
  translation_ai text not null default '',
  change_label text not null default '',
  change_value integer,
  change_is_breakout integer not null default 0,
  imported_at text not null,
  unique(source_file_id, source_row)
);

create table if not exists translation_cache (
  query text primary key,
  translation_ai text not null,
  model text not null,
  updated_at text not null
);

create index if not exists idx_trend_geo on trend_queries(geo);
create index if not exists idx_trend_category on trend_queries(category);
create index if not exists idx_trend_change_value on trend_queries(change_value);
create index if not exists idx_trend_query on trend_queries(query);
"""


def row_to_dict(cursor, row):
    return {column[0]: row[index] for index, column in enumerate(cursor.description)}


def normalize_database_url(value):
    if not value:
        return ""
    if value.startswith("postgres://"):
        return "postgresql://" + value[len("postgres://") :]
    return value


def is_postgres_url(value):
    scheme = urlparse(value or "").scheme
    return scheme in {"postgres", "postgresql"}


def placeholder(database_url=""):
    return "%s" if is_postgres_url(database_url) else "?"


def connect_sqlite(db_path):
    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = row_to_dict
    conn.execute("pragma journal_mode=wal")
    conn.execute("pragma foreign_keys=on")
    return conn


def connect_postgres(database_url):
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as error:
        raise RuntimeError("psycopg is required when DATABASE_URL is set") from error

    return psycopg.connect(normalize_database_url(database_url), row_factory=dict_row)


def connect(db_path=None, database_url=None):
    database_url = normalize_database_url(database_url or os.environ.get("DATABASE_URL", ""))
    if database_url:
        return connect_postgres(database_url)
    return connect_sqlite(db_path)


def ensure_schema(conn, database_url=""):
    if is_postgres_url(database_url):
        for statement in POSTGRES_SCHEMA.strip().split(";"):
            if statement.strip():
                conn.execute(statement)
    else:
        conn.executescript(SQLITE_SCHEMA)


def driver_name(database_url=""):
    return "postgres" if is_postgres_url(database_url) else "sqlite"
